In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.datasets import make_classification

In [26]:
df=make_classification(n_samples=1000)

In [12]:
# pipeline import fron sklearn library
from sklearn.pipeline import Pipeline

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [14]:
step=[("standard_scalar",StandardScaler()),('Classifier',LogisticRegression())]

In [15]:
pipe=Pipeline(step)

In [16]:
pipe

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [27]:
x=df[0]
x

array([[-1.94939228,  0.07745232, -0.46124482, ...,  0.83237795,
         0.24396797, -0.3228023 ],
       [ 0.41776173,  0.63919861, -0.15519968, ...,  2.00590983,
         0.61571001,  1.70722486],
       [ 1.02255196,  0.48337468, -0.43326908, ..., -1.21122557,
        -0.23856731, -0.77815768],
       ...,
       [ 1.31045189, -1.29265748, -0.92360627, ..., -0.85655501,
         1.91229044,  0.33252101],
       [ 1.60735939, -0.65404536, -0.34018079, ..., -2.73713586,
         0.59124544,  0.23353209],
       [-0.94390344, -0.83206276,  0.26451623, ...,  1.15569099,
         0.41858584,  1.00325506]])

In [28]:
y=df[1]
y

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [29]:
x.shape

(1000, 20)

In [30]:
y.shape

(1000,)

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [35]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [36]:
y_pred=pipe.predict(x_test)

In [37]:
y_pred

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1])

# Example 2
Displaying a pipeline with standard scaler, dimesnionality reduction and then estimator

In [38]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [39]:
step2=[("scalar",StandardScaler()),("Decomposition",PCA()),('svc',SVC())]

In [40]:
pipe2=Pipeline(step2)

In [41]:
pipe2

Pipeline(steps=[('scalar', StandardScaler()), ('Decomposition', PCA()),
                ('svc', SVC())])

In [42]:
pipe2.fit(x_train,y_train)

Pipeline(steps=[('scalar', StandardScaler()), ('Decomposition', PCA()),
                ('svc', SVC())])

In [43]:
y_pred2=pipe2.predict(x_test)

In [44]:
y_pred2

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1])

# Complex examples of columns transformer

Numerical Processing pipeline

In [45]:
from sklearn.impute import SimpleImputer

In [47]:
numerical_processor=Pipeline(steps=[('Imputation_mean',SimpleImputer(missing_values=np.nan,strategy='mean',)),
                ('standard_scalar',StandardScaler())])

In [48]:
numerical_processor

Pipeline(steps=[('Imputation_mean', SimpleImputer()),
                ('standard_scalar', StandardScaler())])

# Categorical Processing Pipeline

In [49]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))]

)

In [50]:
categorical_processor

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

# Combine The preprocessing Technique

In [51]:
from sklearn.compose import ColumnTransformer

In [53]:
preprocessor=ColumnTransformer(
    [("Categorical",categorical_processor,["gender","City"]),
     ("Numerical",numerical_processor,['age','height'])]
)


In [54]:
preprocessor

ColumnTransformer(transformers=[('Categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('Numerical',
                                 Pipeline(steps=[('Imputation_mean',
                                                  SimpleImputer()),
                                                 ('standard_scalar',
                                                  StandardScaler())]),
                                 ['age', 'height'])])

In [ ]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())