In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import make_classification

In [4]:
df=make_classification(n_samples=1000)

In [5]:
# pipeline import fron sklearn library
from sklearn.pipeline import Pipeline

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [7]:
step=[("standard_scalar",StandardScaler()),('Classifier',LogisticRegression())]

In [8]:
pipe=Pipeline(step)

In [9]:
pipe

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [10]:
x=df[0]
x

array([[ 0.47632036, -0.52042301, -0.34232817, ..., -1.49516656,
        -0.31962326,  1.23241271],
       [ 0.26869859,  1.18929146,  0.27937035, ...,  1.01635868,
        -1.02796155,  0.12403286],
       [ 0.39086132, -0.64721598, -0.28837006, ..., -0.63871908,
        -0.79852244,  0.36304893],
       ...,
       [ 0.16273945,  1.52629007,  1.13863052, ...,  0.51306895,
         0.63138561,  0.86165142],
       [ 0.90430492, -0.04563789, -1.67254918, ..., -0.10531858,
         0.83479823,  0.56604263],
       [ 0.24559011,  0.45606889, -0.83321339, ...,  1.13482547,
        -0.56435564, -0.90884644]])

In [11]:
y=df[1]
y

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [12]:
x.shape

(1000, 20)

In [13]:
y.shape

(1000,)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [16]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [17]:
y_pred=pipe.predict(x_test)

In [18]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0])

# Example 2
Displaying a pipeline with standard scaler, dimesnionality reduction and then estimator

In [19]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [20]:
step2=[("scalar",StandardScaler()),("Decomposition",PCA()),('svc',SVC())]

In [21]:
pipe2=Pipeline(step2)

In [22]:
pipe2

Pipeline(steps=[('scalar', StandardScaler()), ('Decomposition', PCA()),
                ('svc', SVC())])

In [23]:
pipe2.fit(x_train,y_train)

Pipeline(steps=[('scalar', StandardScaler()), ('Decomposition', PCA()),
                ('svc', SVC())])

In [24]:
y_pred2=pipe2.predict(x_test)

In [25]:
y_pred2

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0])

# Complex examples of columns transformer

Numerical Processing pipeline

In [26]:
from sklearn.impute import SimpleImputer

In [27]:
numerical_processor=Pipeline(steps=[('Imputation_mean',SimpleImputer(missing_values=np.nan,strategy='mean',)),
                ('standard_scalar',StandardScaler())])

In [28]:
numerical_processor

Pipeline(steps=[('Imputation_mean', SimpleImputer()),
                ('standard_scalar', StandardScaler())])

# Categorical Processing Pipeline

In [29]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))]

)

In [30]:
categorical_processor

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

# Combine The preprocessing Technique

In [31]:
from sklearn.compose import ColumnTransformer

In [32]:
preprocessor=ColumnTransformer(
    [("Categorical",categorical_processor,["gender","City"]),
     ("Numerical",numerical_processor,['age','height'])]
)


In [33]:
preprocessor

ColumnTransformer(transformers=[('Categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('Numerical',
                                 Pipeline(steps=[('Imputation_mean',
                                                  SimpleImputer()),
                                                 ('standard_scalar',
                                                  StandardScaler())]),
                                 ['age', 'height'])])

In [34]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())

In [35]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('Categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('Numerical',
                                                  Pipeline(steps=[('Imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('standard_scalar',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])